### PR TITLE
fixes and improvements related to handling file names and paths

### PR DESCRIPTION
**Pull request by rnnr**
after these changes the plugin should work both on unix and windows

### CODE REVIEW

**Comment by orctom** [comment]
@rnnr You still haven't answeed my question, about the stategy, give me reasonable reasons or use cases, or I might have it removed maybe tomorrow.

**Comment by orctom** [comment]
I'm to release version 1.3 this weekend BTW.

**Comment by rnnr** [comment]
Great news :), thanks.

**Comment by orctom** [comment]
Ok, fine, one more time.
I'm to delete ConflictResolutionStrategy, unless you explained to me why it's reasonable, and how would you use it in your team?

**Comment by rnnr** [comment]
Please don't.  Deleting the target directory before start of the generation, aka strategy '**sweep**' is **too risky** approach for us. It's crucial for us to avoid accidental deletion of files in target directory, own or created by somebody else, if there is shared write access to the target directory.

The standard setup in our team will be '**fail**', which stops when it a file exist when the generator is going to write -- it also deletes all files generated so far to prevent littering the target directory with partially generated project.

**Comment by orctom** [comment]
OK, I see.
What are you generating? projects?

**Comment by rnnr** [comment]
Yes, it should be generation of Gradle-based Java projects from templates, that's what your plugin does so well.  

That brings a question -  would it be possible, to change '`@variable@`' tokens in code to something else, e.g. '`__variable__`'  as used for directory names ? Or configurable. The idea is to be able to use the templates as regular projects, so developer changing the template can easily check the code is OK without the need to run the generation.

**Comment by orctom** [comment]
I got ConflictResolutionStrategy deleted eventually, but I give you failIfFileExist=true by default.
Checkout the changes and README.

About the token, I'd say, yes it's possible to be configurable, but how would the configure item looks like? Will it be ugly or silly, and this seems too trivial to me. Create your pr if you wish.

**Pull request merged**
